function Invoke-StaticDataMasking {
<#
.SYNOPSIS
A PowerShell function to statically mask data in char, varchar and/or nvarchar columns using a MD5 hashing function.

.DESCRIPTION
This PowerShell function uses as input a JSON file created by calling the New-DbaDbMaskingConfig PowerShell function.
Data in the columns specified in this file which are of the type char, varchar or nvarchar are envrypted using a MD5
hash.

.PARAMETER SqlInstance
Required. The SQL Server instance of the database that static data masking is to be applied to.

.PARAMETER Database
Required. The database that static data masking is to be applied to.

.PARAMETER DataMaskFile
Required. Absolute path to the JSON file generated by invoking New-DbaDbMaskingConfig. The file can be subsequently editted by
hand to suit the data masking requirements of this function's user. Currently, static data masking is only supported for columns with char, varchar, nvarchar, int and bigint data types.

.EXAMPLE
Invoke-StaticDataMasking -SqlInstance  Z-STN-WIN2016-A\DEVOPSDEV -Database tpch-no-compression -DataMaskFile 'C:\Users\devops\Documents\tpch-no-compression.tables.json'

.NOTES
Note that it has dependencies on the dbatools module which are installed with this module.
#>
    param(
        [parameter(mandatory = $true)] [string] $SqlInstance,
        [parameter(mandatory = $true)] [string] $Database,
        [parameter(mandatory = $true)] [string] $DataMaskFile
    )

    Get-DbaToolsModule

    if ($DataMaskFile.ToString().StartsWith('http')) {
        $tables = Invoke-RestMethod -Uri $DataMaskFile
    }
    else {
        # Check if the destination is accessible
        if (-not (Test-Path -Path $DataMaskFile)) {
            Write-Error "Could not find data mask config file $DataMaskFile"
            Return
        }
    }

    # Get all the items that should be processed
    try {
        $tables = Get-Content -Path $DataMaskFile -ErrorAction Stop | ConvertFrom-Json -ErrorAction Stop
    }
    catch {
        Write-Error "Could not parse masking config file: $DataMaskFile" -ErrorRecord $_
    }

    foreach ($tabletest in $tables.Tables) {
        if ($Table -and $tabletest.Name -notin $Table) {
            continue
        }

        $ColumnIndex = 0
        $UpdateStatement = ""

        foreach ($columntest in $tabletest.Columns) {
            if ($columntest.ColumnType -in 'varchar', 'char', 'nvarchar') {
                if ($ColumnIndex -eq 0) {
                    $UpdateStatement = 'UPDATE ' + $tabletest.Name + ' SET ' + $columntest.Name + ' = SUBSTRING(CONVERT(VARCHAR, HASHBYTES(' + '''' + 'MD5' + '''' + ', ' + $columntest.Name + '), 1), 1, ' + $columntest.MaxValue + ')'
                }
                else {
                    $UpdateStatement += ', ' + $columntest.Name + ' = SUBSTRING(CONVERT(VARCHAR, HASHBYTES(' + '''' + 'MD5' + '''' + ', ' + $columntest.Name + '), 1), 1, ' + $columntest.MaxValue + ')'
                }
            }
            elseif ($columntest.ColumnType -eq 'int') {
                if ($ColumnIndex -eq 0) {
                    $UpdateStatement = 'UPDATE ' + $tabletest.Name + ' SET ' + $columntest.Name + ' = ABS(CHECKSUM(NEWID())) % 2147483647'
                }
                else {
                    $UpdateStatement += ', ' + $columntest.Name + ' = ABS(CHECKSUM(NEWID())) % 2147483647'
                }
            }
            elseif ($columntest.ColumnType -eq 'bigint') {
                if ($ColumnIndex -eq 0) {
                    $UpdateStatement = 'UPDATE ' + $tabletest.Name + ' SET ' + $columntest.Name + ' = ABS(CHECKSUM(NEWID()))'
                }
                else {
                    $UpdateStatement += ', ' + $columntest.Name + ' = ABS(CHECKSUM(NEWID()))'
                }
            }
            else {
                Write-Error "$columntest.ColumnType is not supported, please remove the column $columntest.Name from the $tabletest.Name table"
                Return
            }
            $ColumnIndex += 1
        }

        Write-Verbose "Statically masking table $tabletest.Name using $UpdateStatement"
        Invoke-DbaQuery -ServerInstance $SqlInstance -Database $Database -Query $UpdateStatement -QueryTimeout 999999
    }
}